### ISSUE TITLE
Cannot recast data

### ISSUE THREAD

**Issue by muschellij2** [shaheen-syed/CNN-Non-Wear-Time-Algorithm#13]
File available at https://figshare.com/ndownloader/files/45713466

```python
>>> import pandas as pd
>>> from functions import signal_processing_functions as sig
>>> df = pd.read_csv('75093.csv.gz')
>>> print(df.values)
[['2000-01-08T17:30:00.000Z' 0.123 -0.853 -0.276]
 ['2000-01-08T17:30:00.013Z' 0.29 -0.792 -0.111]
 ['2000-01-08T17:30:00.024Z' 0.402 -0.765 -0.026]
 ...
 ['2000-01-11T19:55:52.312Z' 1.496 0.085 0.736]
 ['2000-01-11T19:55:52.325Z' 1.469 0.1 0.739]
 ['2000-01-11T19:55:52.338Z' 1.469 0.12 0.757]]
>>> df = df[["X", "X", "Z"]]
>>> raw_acc = df.to_numpy()
>>> raw_acc = sig.resample_acceleration(data = raw_acc, from_hz = 80, to_hz = 100, verbose = 1)
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/johnmuschelli/Dropbox/Packages/CNN-Non-Wear-Time-Algorithm/functions/signal_processing_functions.py", line 141, in resample_acceleration
    _, new_data[:,i] = resample(data[:,i], from_hz, to_hz, i, verbose)
       ~~~~~~~~^^^^^
ValueError: could not broadcast input array from shape (26795235,) into shape (26795200,)
```

**Comment by muschellij2** [comment]
The issue is at https://github.com/shaheen-syed/CNN-Non-Wear-Time-Algorithm/blob/232d02e736063e3f6da1ed68c4a9fffbe17f456d/functions/signal_processing_functions.py#L134

Either you can change (this keeps current behavior):
```python
x = resample(data[:,i], from_hz, to_hz, i, verbose) 
x = x[:num_samples]
new_data[:,i] = x
```

Or you need to re-define num_samples:
```r
import math
num_samples =  math.floor(len(raw_acc)/from_hz*to_hz)
```

**Comment by muschellij2** [comment]
Given how `resampy` defines the output

https://github.com/bmcfee/resampy/blob/7c484f8eec54b87e8f566578dc3e48a2be81cc80/resampy/core.py#L114

it should probably be
```python
num_samples = int(len(data) * float(to_hz) / float(from_hz))
```
